version: "3.7"

networks:
  gaia_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe
    image: camunda/zeebe:0.24.2
    environment:
      - ZEEBE_LOG_LEVEL=debug
    ports:
      - "26500:26500"
      - "9600:9600"
    depends_on:
      - elasticsearch
    networks:
      - gaia_network
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.7.1
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - gaia_network